---
meta:

  hosts:
    loggregator_trafficcontroller_z1:
      cf1: (( jobs.loggregator_trafficcontroller_z1.networks.cf1.static_ips.[0] || nil ))
      cf2: (( jobs.loggregator_trafficcontroller_z1.networks.cf2.static_ips.[0] || nil ))

    etcd_z1: (( jobs.etcd_leader_z1.networks.cf1.static_ips.[0] || nil ))

networks: (( merge ))

jobs: 
  - name: etcd_leader_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(1) ))
  - name: etcd_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(2) ))
  - name: etcd_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: (( static_ips(3) ))
  - name: nats_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: (( static_ips(4) ))  
  - name: nats_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(4) ))