meta:

  stemcell:
    name: bosh-openstack-kvm-ubuntu
    version: latest

  loggregator_endpoint:
    z1:
      host: (( "0.loggregator_trafficcontroller_z1.cf1." name ".microbosh" ))
    z2:
      host: (( "0.loggregator_trafficcontroller_z2.cf2." name ".microbosh" ))
    
name: (( merge ))

compilation:
  cloud_properties:
    instance_type: m1.medium

networks: (( merge ))
  # - name: floating
  #   type: vip
  #   cloud_properties: (( merge ))
  # - name: cf1
  #   type: dynamic
  #   cloud_properties:
  #     security_groups:
  #       - default
  # - name: cf2
  #   type: dynamic
  #   cloud_properties:
  #     security_groups:
  #       - default

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

  - name: small_z2
    cloud_properties:
      instance_type: m1.small

  - name: medium_z1
    cloud_properties:
      instance_type: m1.medium

  - name: medium_z2
    cloud_properties:
      instance_type: m1.medium

  - name: large_z1
    cloud_properties:
      instance_type: m1.large

  - name: large_z2
    cloud_properties:
      instance_type: m1.medium

  - name: runner_z1
    cloud_properties:
      instance_type: m1.large

  - name: runner_z2
    cloud_properties:
      instance_type: m1.large

  - name: router_z1
    cloud_properties:
      instance_type: m1.small

  - name: router_z2
    cloud_properties:
      instance_type: m1.small


jobs:
  - name: logs_z1
    instances: 1
    persistent_disk: 8192
    networks:
      - name: cf1
        static_ips: ~

  - name: logs_z2
    instances: 1
    persistent_disk: 8192
    networks:
      - name: cf2
        static_ips: ~

  - name: nats_z1
    instances: 0
    networks:
      - name: cf1
        static_ips: ~

  - name: nats_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: ~

  - name: nfs_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: ~

  - name: postgres_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: ~

  - name: router_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: ~

  - name: router_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: ~

  - name: loggregator_z1
    instances: 2
    networks:
      - name: cf1
        static_ips: ~

  - name: loggregator_z2
    instances: 2
    networks:
      - name: cf2
        static_ips: ~

  - name: loggregator_trafficcontroller_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: ~

  - name: loggregator_trafficcontroller_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: ~

  - name: ha_proxy_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: ~

  - name: etcd_leader_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: ~

  - name: etcd_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: ~

  - name: etcd_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: ~

  # using login template, that supports self-signed certs
  - name: login_z1
    template: login

properties:
  domain: "1.2.3.4.xip.io"
  system_domain_organization: pivotal

  ccdb:
    db_scheme: postgres
    address: (( properties.databases.address ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: admin
    databases:
      - tag: cc
        name: ccdb
        citext: true

  uaadb:
    db_scheme: postgresql
    address: (( properties.databases.address ))
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  databases:
    db_scheme: postgres
    address: "0.postgres_z1.cf1.test.microbosh"
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: admin
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

  uaa:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m

  login:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    protocol: http

